import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import bcrypt from 'bcryptjs';
import { Company, Driver, Delivery, DeliveryEvent, LocationCoords, FoodStore, FoodCategory, FoodProduct, FoodShippingRate, FoodOrder } from '../src/types';
import { WithdrawalRequest } from './legal/types';

export type UserRole = 'SUPER_ADMIN' | 'COMPANY_ADMIN' | 'DISPATCHER' | 'KITCHEN' | 'DRIVER' | 'CLIENT';
export interface UserRecord { id:string; email:string; passwordHash:string; name:string; role:UserRole; companyId:string; driverId?:string; phone?:string; createdAt:number; active:boolean; privacyPolicyAccepted:boolean; privacyPolicyAcceptedAt:number; termsOfServiceAccepted:boolean; termsOfServiceAcceptedAt?:number; }
export type UserRecordInput = Omit<UserRecord,'privacyPolicyAccepted'|'privacyPolicyAcceptedAt'|'termsOfServiceAccepted'> & Partial<Pick<UserRecord,'privacyPolicyAccepted'|'privacyPolicyAcceptedAt'|'termsOfServiceAccepted'|'termsOfServiceAcceptedAt'>>;
export interface InvitationRecord { id:string; email:string; tokenHash:string; companyId:string; role:UserRole; expiresAt:number; used:boolean; usedAt?:number; createdAt:number; }
export interface PasswordResetRecord { id:string; email:string; tokenHash:string; expiresAt:number; used:boolean; usedAt?:number; createdAt:number; }
export function validatePassword(password:string):{valid:boolean;error?:string}{ if(!password||typeof password!=='string')return{valid:false,error:'Contraseña requerida'}; if(password.length<8)return{valid:false,error:'La contraseña debe tener al menos 8 caracteres'}; const weak=['password','12345678','123456789','qwerty123','123456784','123456785']; if(weak.includes(password.toLowerCase())||/^(123456|password|qwerty)/i.test(password))return{valid:false,error:'La contraseña es demasiado débil o común. Por favor elija una más segura.'}; return{valid:true}; }
export interface LocationSessionRecord { id:string; deliveryId:string; companyId:string; sessionTokenHash:string; createdAt:number; expiresAt:number; authorizedAt?:number; endedAt?:number; status:'ACTIVE'|'EXPIRED'|'PURGED'|'CANCELLED'; recipientLocation?:LocationCoords|null; }
export interface DatabaseSchema { version:number; companies:Company[]; users:UserRecord[]; drivers:Driver[]; deliveries:Delivery[]; location_sessions:LocationSessionRecord[]; events:DeliveryEvent[]; driver_locations:{id:string;deliveryId?:string;driverId:string;companyId:string;latitude:number;longitude:number;accuracy:number;speed?:number|null;timestamp:number}[]; food_stores?:FoodStore[]; food_categories?:FoodCategory[]; food_products?:FoodProduct[]; food_shipping_rates?:FoodShippingRate[]; food_orders?:FoodOrder[]; invitations?:InvitationRecord[]; password_resets?:PasswordResetRecord[]; commerce_categories?:any[]; commerce_products?:any[]; commerce_customers?:any[]; commerce_stock_movements?:any[]; commerce_cash_sessions?:any[]; commerce_sales?:any[]; commerce_invoices?:any[]; withdrawal_requests?:WithdrawalRequest[]; }
const DATA_DIR=path.join(process.cwd(),'data'); const BACKUPS_DIR=path.join(DATA_DIR,'backups'); const DB_FILE=path.join(DATA_DIR,'ubika_persistent_db.json');
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true}); if(!fs.existsSync(BACKUPS_DIR))fs.mkdirSync(BACKUPS_DIR,{recursive:true});
let dbState:DatabaseSchema; let lastBackupTime=0;
export function hashToken(token:string):string{return crypto.createHash('sha256').update(token).digest('hex');}
export function createBackup():string|null{if(!dbState)return null;try{const backupFile=path.join(BACKUPS_DIR,`ubika_backup_${Date.now()}.json`);fs.writeFileSync(backupFile,JSON.stringify(dbState,null,2),'utf-8');const files=fs.readdirSync(BACKUPS_DIR).filter(f=>f.startsWith('ubika_backup_')&&f.endsWith('.json')).sort();while(files.length>10){const oldest=files.shift();if(oldest)fs.unlinkSync(path.join(BACKUPS_DIR,oldest));}return backupFile;}catch(err){console.error('[DB Backup Error]:',err);return null;}}
function createInitialSeedData():DatabaseSchema{const adminPassword=process.env.INITIAL_ADMIN_PASSWORD;if(!adminPassword)return{version:2,companies:[],users:[],drivers:[],deliveries:[],location_sessions:[],events:[],driver_locations:[],food_stores:[],food_categories:[],food_products:[],food_shipping_rates:[],food_orders:[]};const salt=bcrypt.genSaltSync(10);const hash=bcrypt.hashSync(adminPassword,salt);const company={id:'comp_default_admin',name:'Sede Central',category:'Mensajería y Cadetería' as const,address:'Ubicación Principal',phone:'',city:'',activeOrdersCount:0,totalDriversCount:0,businessType:'LOGISTICS' as const,foodEnabled:false};const user={id:'usr_admin_master',email:'admin@ubika.local',passwordHash:hash,name:'Administrador Principal',role:'SUPER_ADMIN' as const,companyId:'comp_default_admin',createdAt:Date.now(),active:true,privacyPolicyAccepted:true,privacyPolicyAcceptedAt:Date.now(),termsOfServiceAccepted:true,termsOfServiceAcceptedAt:Date.now()};return{version:2,companies:[company],users:[user],drivers:[],deliveries:[],location_sessions:[],events:[],driver_locations:[],food_stores:[],food_categories:[],food_products:[],food_shipping_rates:[],food_orders:[],invitations:[],password_resets:[]};}
export function injectTestFixtures(){/* test fixtures intentionally managed by test setup; production startup does not inject demo records. */}
function runFoodMigration(db:DatabaseSchema):boolean{let changed=false;db.food_stores=db.food_stores||[];db.food_categories=db.food_categories||[];db.food_products=db.food_products||[];db.food_shipping_rates=db.food_shipping_rates||[];db.food_orders=db.food_orders||[];if((db.version||1)<2){db.version=2;changed=true;}return changed;}
export function loadDatabase():DatabaseSchema{if(dbState)return dbState;const adminPassword=process.env.INITIAL_ADMIN_PASSWORD;if(!adminPassword)throw new Error('INITIAL_ADMIN_PASSWORD is required. Please set this environment variable.');if(fs.existsSync(DB_FILE)){let raw:string;try{raw=fs.readFileSync(DB_FILE,'utf-8');}catch(readErr:any){throw new Error(`FATAL_DB_READ_ERROR: Archivo existente en ${DB_FILE} no puede ser leído: ${readErr.message}`);}try{dbState=JSON.parse(raw);}catch(_parseErr:any){throw new Error(`FATAL_DB_CORRUPTED: El archivo existente en ${DB_FILE} está corrupto. Inicialización detenida para preservar datos.`);}if(!dbState||typeof dbState!=='object'||!Array.isArray(dbState.users)||!Array.isArray(dbState.companies))throw new Error(`FATAL_DB_INVALID_STRUCTURE: Archivo en ${DB_FILE} no posee estructura de base de datos válida.`);dbState.food_stores=dbState.food_stores||[];dbState.food_categories=dbState.food_categories||[];dbState.food_products=dbState.food_products||[];dbState.food_shipping_rates=dbState.food_shipping_rates||[];dbState.food_orders=dbState.food_orders||[];dbState.invitations=dbState.invitations||[];dbState.password_resets=dbState.password_resets||[];dbState.commerce_categories=dbState.commerce_categories||[];dbState.commerce_products=dbState.commerce_products||[];dbState.commerce_customers=dbState.commerce_customers||[];dbState.commerce_stock_movements=dbState.commerce_stock_movements||[];dbState.commerce_cash_sessions=dbState.commerce_cash_sessions||[];dbState.commerce_sales=dbState.commerce_sales||[];dbState.commerce_invoices=dbState.commerce_invoices||[];const changed=runFoodMigration(dbState);if(changed)saveDatabaseSync();return dbState;}dbState=createInitialSeedData();saveDatabaseSync();return dbState;}
export function saveDatabaseSync(){if(!dbState)return;const tempFile=`${DB_FILE}.tmp.${Date.now()}`;fs.writeFileSync(tempFile,JSON.stringify(dbState,null,2),'utf-8');fs.renameSync(tempFile,DB_FILE);const now=Date.now();if(now-lastBackupTime>30*60*1000){lastBackupTime=now;createBackup();}}
loadDatabase();
export const db={
 getCompanyById:(id:string)=>dbState.companies.find(c=>c.id===id),getAllCompanies:()=>dbState.companies,createCompany:(c:Company)=>{dbState.companies.push(c);saveDatabaseSync();return c;},updateCompany:(id:string,u:Partial<Company>)=>{const i=dbState.companies.findIndex(c=>c.id===id);if(i<0)return null;dbState.companies[i]={...dbState.companies[i],...u};saveDatabaseSync();return dbState.companies[i];},
 getUserByEmail:(e:string)=>dbState.users.find(u=>u.email.toLowerCase()===e.toLowerCase()),getUserById:(id:string)=>dbState.users.find(u=>u.id===id),getUsersByCompany:(cid:string)=>dbState.users.filter(u=>u.companyId===cid),createUser:(u:UserRecordInput)=>{const createdAt=u.createdAt||Date.now();const n:UserRecord={...u,privacyPolicyAccepted:u.privacyPolicyAccepted??true,privacyPolicyAcceptedAt:u.privacyPolicyAcceptedAt??createdAt,termsOfServiceAccepted:u.termsOfServiceAccepted??true,termsOfServiceAcceptedAt:u.termsOfServiceAcceptedAt??createdAt};dbState.users.push(n);saveDatabaseSync();return n;},updateUser:(id:string,u:Partial<UserRecord>)=>{const i=dbState.users.findIndex(x=>x.id===id);if(i<0)return null;dbState.users[i]={...dbState.users[i],...u};saveDatabaseSync();return dbState.users[i];},
 createInvitation:(inv:InvitationRecord)=>{dbState.invitations=dbState.invitations||[];dbState.invitations.forEach(i=>{if(i.email.toLowerCase()===inv.email.toLowerCase()&&!i.used){i.used=true;i.usedAt=Date.now();}});dbState.invitations.push(inv);saveDatabaseSync();return inv;},getInvitationByHash:(h:string)=>{dbState.invitations=dbState.invitations||[];return dbState.invitations.find(i=>i.tokenHash===h);},updateInvitation:(id:string,u:Partial<InvitationRecord>)=>{dbState.invitations=dbState.invitations||[];const i=dbState.invitations.findIndex(x=>x.id===id);if(i<0)return null;dbState.invitations[i]={...dbState.invitations[i],...u};saveDatabaseSync();return dbState.invitations[i];},createPasswordReset:(pr:PasswordResetRecord)=>{dbState.password_resets=dbState.password_resets||[];dbState.password_resets.forEach(p=>{if(p.email.toLowerCase()===pr.email.toLowerCase()&&!p.used){p.used=true;p.usedAt=Date.now();}});dbState.password_resets.push(pr);saveDatabaseSync();return pr;},getPasswordResetByHash:(h:string)=>{dbState.password_resets=dbState.password_resets||[];return dbState.password_resets.find(p=>p.tokenHash===h);},updatePasswordReset:(id:string,u:Partial<PasswordResetRecord>)=>{dbState.password_resets=dbState.password_resets||[];const i=dbState.password_resets.findIndex(x=>x.id===id);if(i<0)return null;dbState.password_resets[i]={...dbState.password_resets[i],...u};saveDatabaseSync();return dbState.password_resets[i];},
 getDriversByCompany:(cid:string)=>dbState.drivers.filter(d=>d.companyId===cid),getDriverById:(id:string)=>dbState.drivers.find(d=>d.id===id),createDriver:(d:Driver)=>{dbState.drivers.push(d);saveDatabaseSync();return d;},updateDriver:(id:string,u:Partial<Driver>)=>{const i=dbState.drivers.findIndex(d=>d.id===id);if(i<0)return null;dbState.drivers[i]={...dbState.drivers[i],...u};saveDatabaseSync();return dbState.drivers[i];},
 getDeliveriesByCompany:(cid:string)=>dbState.deliveries.filter(d=>d.companyId===cid),getDeliveriesByDriver:(id:string)=>dbState.deliveries.filter(d=>d.driverId===id),getDeliveryById:(id:string)=>dbState.deliveries.find(d=>d.id===id),createDelivery:(d:Delivery)=>{dbState.deliveries.unshift(d);saveDatabaseSync();return d;},updateDelivery:(id:string,u:Partial<Delivery>)=>{const i=dbState.deliveries.findIndex(d=>d.id===id);if(i<0)return null;dbState.deliveries[i]={...dbState.deliveries[i],...u};saveDatabaseSync();return dbState.deliveries[i];},
 createLocationSession:(s:LocationSessionRecord)=>{dbState.location_sessions.push(s);saveDatabaseSync();return s;},getSessionByToken:(token:string):LocationSessionRecord|undefined=>{const h=hashToken(token);const s=dbState.location_sessions.find(x=>x.sessionTokenHash===h);if(!s)return undefined;if(s.status==='CANCELLED'||s.status==='PURGED')return undefined;if(Date.now()>=s.expiresAt){s.status='EXPIRED';s.endedAt=s.endedAt||Date.now();s.recipientLocation=null;saveDatabaseSync();return undefined;}return s;},updateSession:(id:string,u:Partial<LocationSessionRecord>)=>{const i=dbState.location_sessions.findIndex(s=>s.id===id);if(i<0)return null;dbState.location_sessions[i]={...dbState.location_sessions[i],...u};saveDatabaseSync();return dbState.location_sessions[i];},
 getEventsByCompany:(cid:string)=>dbState.events.filter(e=>(e as any).companyId===cid).sort((a,b)=>b.timestamp-a.timestamp),getEventsByDelivery:(id:string)=>dbState.events.filter(e=>e.deliveryId===id).sort((a,b)=>a.timestamp-b.timestamp),createEvent:(e:DeliveryEvent)=>{dbState.events.unshift(e);saveDatabaseSync();return e;},
 recordDriverLocation:(r:{driverId:string;deliveryId?:string;companyId:string;latitude:number;longitude:number;accuracy:number;speed?:number|null;timestamp:number})=>{dbState.driver_locations.push({id:`loc_${crypto.randomUUID()}`,...r});if(dbState.driver_locations.length>5000)dbState.driver_locations=dbState.driver_locations.slice(-3000);saveDatabaseSync();},getDriverLocationHistory:(id:string,since?:number)=>dbState.driver_locations.filter(l=>l.driverId===id&&(!since||l.timestamp>=since)).sort((a,b)=>a.timestamp-b.timestamp),
 getFoodStoreByCompanyId:(cid:string)=> (dbState.food_stores||[]).find(s=>s.companyId===cid),upsertFoodStore:(s:FoodStore)=>{if(!dbState.food_stores)dbState.food_stores=[];const i=dbState.food_stores.findIndex(x=>x.companyId===s.companyId);if(i<0)dbState.food_stores.push(s);else dbState.food_stores[i]={...dbState.food_stores[i],...s,updatedAt:Date.now()};saveDatabaseSync();return s;},getFoodCategoriesByCompanyId:(cid:string)=>(dbState.food_categories||[]).filter(c=>c.companyId===cid).sort((a,b)=>(a.displayOrder??a.sortOrder??999)-(b.displayOrder??b.sortOrder??999)),createFoodCategory:(c:FoodCategory)=>{if(!dbState.food_categories)dbState.food_categories=[];const n={...c,displayOrder:c.displayOrder??c.sortOrder??1,active:c.active!==undefined?c.active:(c.isActive!==undefined?c.isActive:true),createdAt:c.createdAt||Date.now(),updatedAt:Date.now()};dbState.food_categories.push(n);saveDatabaseSync();return n;},updateFoodCategory:(id:string,u:Partial<FoodCategory>)=>{if(!dbState.food_categories)return null;const i=dbState.food_categories.findIndex(c=>c.id===id);if(i<0)return null;dbState.food_categories[i]={...dbState.food_categories[i],...u,updatedAt:Date.now()};saveDatabaseSync();return dbState.food_categories[i];},deleteFoodCategory:(id:string)=>{if(!dbState.food_categories)return false;const n=dbState.food_categories.length;dbState.food_categories=dbState.food_categories.filter(c=>c.id!==id);if(dbState.food_categories.length<n)saveDatabaseSync();return dbState.food_categories.length<n;},
 getFoodProductsByCompanyId:(cid:string)=>(dbState.food_products||[]).filter(p=>p.companyId===cid).sort((a,b)=>a.displayOrder-b.displayOrder),getFoodProductById:(id:string)=>(dbState.food_products||[]).find(p=>p.id===id),createFoodProduct:(p:FoodProduct)=>{if(!dbState.food_products)dbState.food_products=[];dbState.food_products.push(p);saveDatabaseSync();return p;},updateFoodProduct:(id:string,u:Partial<FoodProduct>)=>{if(!dbState.food_products)return null;const i=dbState.food_products.findIndex(p=>p.id===id);if(i<0)return null;dbState.food_products[i]={...dbState.food_products[i],...u};saveDatabaseSync();return dbState.food_products[i];},deleteFoodProduct:(id:string)=>{if(!dbState.food_products)return false;const n=dbState.food_products.length;dbState.food_products=dbState.food_products.filter(p=>p.id!==id);if(dbState.food_products.length<n)saveDatabaseSync();return dbState.food_products.length<n;},
 getFoodShippingRateByCompanyId:(cid:string)=>(dbState.food_shipping_rates||[]).find(r=>r.companyId===cid),upsertFoodShippingRate:(r:FoodShippingRate)=>{if(!dbState.food_shipping_rates)dbState.food_shipping_rates=[];const i=dbState.food_shipping_rates.findIndex(x=>x.companyId===r.companyId);if(i<0)dbState.food_shipping_rates.push(r);else dbState.food_shipping_rates[i]={...dbState.food_shipping_rates[i],...r};saveDatabaseSync();return r;},
 getFoodOrdersByCompanyId:(cid:string)=>(dbState.food_orders||[]).filter(o=>o.companyId===cid).sort((a,b)=>b.createdAt-a.createdAt),getFoodOrderById:(id:string)=>(dbState.food_orders||[]).find(o=>o.id===id),getFoodOrderByPickupCode:(code:string)=>(dbState.food_orders||[]).find(o=>o.pickupCode===code),createFoodOrder:(o:FoodOrder)=>{if(!dbState.food_orders)dbState.food_orders=[];dbState.food_orders.unshift(o);saveDatabaseSync();return o;},updateFoodOrder:(id:string,u:Partial<FoodOrder>)=>{if(!dbState.food_orders)return null;const i=dbState.food_orders.findIndex(o=>o.id===id);if(i<0)return null;dbState.food_orders[i]={...dbState.food_orders[i],...u,updatedAt:Date.now()};saveDatabaseSync();return dbState.food_orders[i];},
 createWithdrawalRequest:(r:WithdrawalRequest)=>{if(!dbState.withdrawal_requests)dbState.withdrawal_requests=[];dbState.withdrawal_requests.unshift(r);saveDatabaseSync();return r;},getWithdrawalRequest:(id:string)=>{const r=(dbState.withdrawal_requests||[]).find(x=>x.id===id);return r||null;},updateWithdrawalRequest:(id:string,u:Partial<WithdrawalRequest>)=>{if(!dbState.withdrawal_requests)return null;const i=dbState.withdrawal_requests.findIndex(r=>r.id===id);if(i<0)return null;dbState.withdrawal_requests[i]={...dbState.withdrawal_requests[i],...u,updatedAt:Date.now()};saveDatabaseSync();return dbState.withdrawal_requests[i];},getWithdrawalRequestsByCompany:(cid:string)=>(dbState.withdrawal_requests||[]).filter(r=>r.companyId===cid),getAllWithdrawalRequests:()=>dbState.withdrawal_requests||[],
 createBackup:()=>{saveDatabaseSync();const name=`ubika_backup_${Date.now()}.json`;fs.copyFileSync(DB_FILE,path.join(DATA_DIR,name));return name;},getRawState:()=>dbState,reloadFromDisk:()=>{dbState=undefined as any;return loadDatabase();}
};
